# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='submitter',
            field=models.TextField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
