# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20160104_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submitter',
            field=models.TextField(default=b'', max_length=20),
        ),
    ]
